// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	entity "hospitalApi/pkg/entity"
	errs "hospitalApi/pkg/errs"

	mock "github.com/stretchr/testify/mock"

	model "hospitalApi/pkg/model"
)

// IPatientService is an autogenerated mock type for the IPatientService type
type IPatientService struct {
	mock.Mock
}

// Get provides a mock function with given fields: input
func (_m *IPatientService) Get(input model.PatientCriteria) ([]model.Patient, *errs.Error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Patient
	var r1 *errs.Error
	if rf, ok := ret.Get(0).(func(model.PatientCriteria) ([]model.Patient, *errs.Error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(model.PatientCriteria) []model.Patient); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(model.PatientCriteria) *errs.Error); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errs.Error)
		}
	}

	return r0, r1
}

// MappingEntityToModel provides a mock function with given fields: input
func (_m *IPatientService) MappingEntityToModel(input entity.Patient) *model.Patient {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for MappingEntityToModel")
	}

	var r0 *model.Patient
	if rf, ok := ret.Get(0).(func(entity.Patient) *model.Patient); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Patient)
		}
	}

	return r0
}

// NewIPatientService creates a new instance of IPatientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPatientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPatientService {
	mock := &IPatientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
